name: Release process

on:
  push:
      branches: [ develop ]
jobs:
  check-commit:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^RELEASE:*'
          error: 'The last push of this feature is not ready to be merged with the main branch.'
  create-release:
    name: Create release branch
    needs: check-commit
    runs-on: ubuntu-latest
    steps:
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release'